version: '3.2'

services:
  mat-reporting-api:
    image: mat-reporting-api
    build:
      context: mat-reporting-api/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  
  mat-reporting-api-test:
    image: mat-reporting-api-test
    build:
      context: .
      dockerfile: mat-reporting-api.Tests/Dockerfile
    