version: '3.2'

services:
  mat-reporting-api:
    image: mat-reporting-api
    build:
      context: .
      dockerfile: mat-reporting-api/Dockerfile
    ports:
      - 3000:3000
  
  mat-reporting-api-test:
    image: mat-reporting-api-test
    build:
      context: .
      dockerfile: mat-reporting-api.Tests/Dockerfile
    environment:
        - MONGO_CONN_STRING=mongodb://mongo-db:27017
    links:
      - mongo-db
  mongo-db:
    image: mongo:3.6
    ports:
      - 1433:27017