version: 2.1

jobs:
  check:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: docker-compose build mat-reporting-api-test
      - run:
          name: Run tests
          command: docker-compose up mat-reporting-api-test

 workflows:
  build-and-test:
      jobs:
      - check