version: 2.1

jobs:
  check:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: build
          command: docker-compose build mat-reporting-api-test
      - run:
          name: Run tests
          command: docker-compose up mat-reporting-api-test

workflows:
  build:
      jobs:
      - check
