version: 2.1


jobs:
  check:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: build
          command: docker-compose build base-api-test
      - run:
          name: Run tests
          command: docker-compose up base-api-test

workflows:
  build:
      jobs:
      - check
